/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "main.h"

void wait_for_unpress(GPIOx_IDR_t *GPIOA_IDR_ptr);

int main(void)
{
	initialise_monitor_handles();

	// Variables initialization //
	//////////////////////////////
	//   Pointers to registers  //
	RCC_AHB2ENR_t volatile * const RCC_AHB2ENR_ptr 		 = ADDR_RCC_AHB2ENR;
	GPIOx_MODER_t volatile * const GPIOA_MODER_ptr 		 = ADDR_GPIOA_MODER;
	GPIOx_PUPDR_t volatile * const GPIOA_PUPDR_ptr 		 = ADDR_GPIOA_PUPDR;
	GPIOx_ODR_t   volatile * const GPIOA_ODR_ptr   		 = ADDR_GPIOA_ODR;
	GPIOx_IDR_t   volatile const * const GPIOA_IDR_ptr   = ADDR_GPIOA_IDR;

	//Enable RCC for GPIOA
	RCC_AHB2ENR_ptr->GPIOAEN = PIN_STATE_HIGH;

	//Set ROWS to OUTPUT and COLS to INPUT
	GPIOA_MODER_ptr->pin_2 = PIN_MODE_OUTPUT;
	GPIOA_MODER_ptr->pin_7 = PIN_MODE_OUTPUT;
	GPIOA_MODER_ptr->pin_6 = PIN_MODE_OUTPUT;
	GPIOA_MODER_ptr->pin_5 = PIN_MODE_OUTPUT;
	GPIOA_MODER_ptr->pin_4 = PIN_MODE_INPUT;
	GPIOA_MODER_ptr->pin_3 = PIN_MODE_INPUT;
	GPIOA_MODER_ptr->pin_1 = PIN_MODE_INPUT;
	GPIOA_MODER_ptr->pin_0 = PIN_MODE_INPUT;

	//Enable pull-up resistor for COLS
	GPIOA_PUPDR_ptr->pin_4 = PIN_PULL_UP_EN;
	GPIOA_PUPDR_ptr->pin_3 = PIN_PULL_UP_EN;
	GPIOA_PUPDR_ptr->pin_1 = PIN_PULL_UP_EN;
	GPIOA_PUPDR_ptr->pin_0 = PIN_PULL_UP_EN;

	//Set all ROWs to HIGH state
	ROW_1 = PIN_STATE_HIGH;
	ROW_2 = PIN_STATE_HIGH;
	ROW_3 = PIN_STATE_HIGH;
	ROW_4 = PIN_STATE_HIGH;

    /* Loop forever */
	for(;;) {

		//Read ROW_1
		ROW_1 = PIN_STATE_LOW;
		if(COL_1 == PIN_STATE_LOW) {
			DELAY;
			printf("1\n");
			WAIT_FOR_COL_1_UNPRESS
		}
		if(COL_2 == PIN_STATE_LOW) {
			DELAY;
			printf("2\n");
			WAIT_FOR_COL_2_UNPRESS
		}
		if(COL_3 == PIN_STATE_LOW) {
			DELAY;
			printf("3\n");
			WAIT_FOR_COL_3_UNPRESS
		}
		if(COL_4 == PIN_STATE_LOW) {
			DELAY;
			printf("A\n");
			WAIT_FOR_COL_4_UNPRESS
		}
		ROW_1 = PIN_STATE_HIGH;

		//Read ROW_2
		ROW_2 = PIN_STATE_LOW;
		if(COL_1 == PIN_STATE_LOW) {
			DELAY;
			printf("4\n");
			WAIT_FOR_COL_1_UNPRESS
		}
		if(COL_2 == PIN_STATE_LOW) {
			DELAY;
			printf("5\n");
			WAIT_FOR_COL_2_UNPRESS
		}
		if(COL_3 == PIN_STATE_LOW) {
			DELAY;
			printf("6\n");
			WAIT_FOR_COL_3_UNPRESS
		}
		if(COL_4 == PIN_STATE_LOW) {
			DELAY;
			printf("B\n");
			WAIT_FOR_COL_4_UNPRESS
		}
		ROW_2 = PIN_STATE_HIGH;

		//Read ROW_3
		ROW_3 = PIN_STATE_LOW;
		if(COL_1 == PIN_STATE_LOW) {
			DELAY;
			printf("7\n");
			WAIT_FOR_COL_1_UNPRESS
		}
		if(COL_2 == PIN_STATE_LOW) {
			DELAY;
			printf("8\n");
			WAIT_FOR_COL_2_UNPRESS
		}
		if(COL_3 == PIN_STATE_LOW) {
			DELAY;
			printf("9\n");
			WAIT_FOR_COL_3_UNPRESS
		}
		if(COL_4 == PIN_STATE_LOW) {
			DELAY;
			printf("C\n");
			WAIT_FOR_COL_4_UNPRESS
		}
		ROW_3 = PIN_STATE_HIGH;

		//Read ROW_4
		ROW_4 = PIN_STATE_LOW;
		if(COL_1 == PIN_STATE_LOW) {
			DELAY;
			printf("*\n");
			WAIT_FOR_COL_1_UNPRESS
		}
		if(COL_2 == PIN_STATE_LOW) {
			DELAY;
			printf("0\n");
			WAIT_FOR_COL_2_UNPRESS
		}
		if(COL_3 == PIN_STATE_LOW) {
			DELAY;
			printf("#\n");
			WAIT_FOR_COL_3_UNPRESS
		}
		if(COL_4 == PIN_STATE_LOW) {
			DELAY;
			printf("D\n");
			WAIT_FOR_COL_4_UNPRESS
		}
		ROW_4 = PIN_STATE_HIGH;

	}

}
